feat: bump to babel 7.7.7, reproducing regression
```
$ yarn start
$ babel-node --require foo.js bar.js
./babel-bug-introduced-by-10871/node_modules/resolve/lib/sync.js:92
    throw err;
    ^

Error: Cannot find module 'foo.js' from './babel-bug-introduced-by-10871'
    at Function.resolveSync [as sync] (./babel-bug-introduced-by-10871/node_modules/resolve/lib/sync.js:90:15)
    at Object.<anonymous> (./babel-bug-introduced-by-10871/node_modules/@babel/node/lib/_babel-node.js:158:32)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND'
```